{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_basic.py:11: AssertionError"}, "description": "this test fails", "start": 1588904560015, "stop": 1588904560015, "uuid": "0be97eea-aa3c-47f8-afea-b60851433d61", "historyId": "d941bd9ed78229e9f1c8e00795c8a8d8", "testCaseId": "8619591187aa574ffa27ec5688d6603e", "fullName": "test_basic#test_failure", "labels": [{"name": "suite", "value": "test_basic"}, {"name": "host", "value": "pinrongdeMacBook-Pro.local"}, {"name": "thread", "value": "88630-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_basic"}]}