{
  "uid" : "231bfcece02a56cd",
  "name" : "test_xfail_expected_failure",
  "fullName" : "test_failure#test_xfail_expected_failure",
  "historyId" : "4e6959817de09b843e6633ce25627cdb",
  "time" : {
    "start" : 1587454109954,
    "stop" : 1587454109955,
    "duration" : 1
  },
  "description" : "this test is an xfail that will be marked as expected failure",
  "descriptionHtml" : "<p>this test is an xfail that will be marked as expected failure</p>\n",
  "status" : "skipped",
  "statusMessage" : "AssertionError: assert False",
  "statusTrace" : "@pytest.mark.xfail(condition=lambda: True, reason='this test is expecting failure')\n    def test_xfail_expected_failure():\n        \"\"\"this test is an xfail that will be marked as expected failure\"\"\"\n>       assert False\nE       assert False\n\ntest_failure.py:7: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "test_failure"
  }, {
    "name" : "host",
    "value" : "pinrongdeMacBook-Pro.local"
  }, {
    "name" : "thread",
    "value" : "83258-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_failure"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "231bfcece02a56cd.json",
  "parameterValues" : [ ]
}